# Generated by Django 3.1.3 on 2020-12-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم : ')),
                ('sub_title', models.CharField(max_length=50, verbose_name='عنوان الموضوع : ')),
                ('address', models.CharField(max_length=50, verbose_name='العنوان:')),
                ('address_detail', models.CharField(max_length=50, verbose_name='العنوان بالتفصيل')),
                ('phone', models.CharField(max_length=50, verbose_name='ر:قم الهاتف')),
                ('working_hours', models.CharField(max_length=50, verbose_name='ساعات العمل:')),
                ('waitting_time', models.IntegerField(blank=True, null=True, verbose_name='وقت الانتظار : ')),
                ('doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='نبذة :')),
                ('who_i', models.TextField(blank=True, max_length=250, null=True, verbose_name='من أنا : ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف : ')),
                ('join_now', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :')),
                ('type_person', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=50, verbose_name='النوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='الصورة الشخصية')),
                ('specialist_doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name=' التخصص:')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
