# Generated by Django 3.1.3 on 2020-12-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('جلدية', 'جلدية'), ('مخ واعصاب', 'مخ واعصاب'), ('جراحة', 'جراحة'), ('ولادة', 'ولادة'), ('قلب', 'قلب'), ('عظام', 'عظام'), ('اشعة', 'اشعة'), ('عيون', 'عيون')], max_length=50, null=True, verbose_name='نبذة :'),
        ),
    ]
