# Generated by Django 3.1.3 on 2020-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201222_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('عظام', 'عظام'), ('اشعة', 'اشعة'), ('قلب', 'قلب'), ('جلدية', 'جلدية'), ('عيون', 'عيون'), ('مخ واعصاب', 'مخ واعصاب'), ('ولادة', 'ولادة'), ('جراحة', 'جراحة')], max_length=50, null=True, verbose_name=' دكتور ؟:'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_title',
            field=models.CharField(max_length=50, verbose_name='نبذة : '),
        ),
    ]
