# Generated by Django 3.1.3 on 2020-12-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201222_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('ولادة', 'ولادة'), ('مخ واعصاب', 'مخ واعصاب'), ('عظام', 'عظام'), ('جلدية', 'جلدية'), ('اشعة', 'اشعة'), ('جراحة', 'جراحة'), ('قلب', 'قلب'), ('عيون', 'عيون')], max_length=50, null=True, verbose_name=' دكتور ؟:'),
        ),
    ]
