# Generated by Django 3.1.3 on 2020-12-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201222_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50, verbose_name='اللقب  '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('ولادة', 'ولادة'), ('قلب', 'قلب'), ('عظام', 'عظام'), ('مخ واعصاب', 'مخ واعصاب'), ('جلدية', 'جلدية'), ('عيون', 'عيون'), ('جراحة', 'جراحة'), ('اشعة', 'اشعة')], max_length=50, null=True, verbose_name=' دكتور ؟:'),
        ),
    ]
